{
	"error":0,
	"errorSummary":"",
	"errorDescription":"",
	"errorIsWarning":false,
	"silentError":0,
	"payload":{
		"url":"/save.php?controller=department&action=add",
		"fields":[
			{
				"name":"name",
				"id":"name",
				"label":"Name",
				"tagname":"input",
				"type":"text",
				"required":true
			},
			{
				"name":"company",
				"id":"company",
				"label":"Company",
				"tagname":"select",
				"source":"fillComboboxCompany.js"
			},
			{
				"name":"color",
				"id":"color",
				"label":"Color",
				"tagname":"input",
				"type":"text"
			}
		]
	},
	"resource_map":null,
	"css":[],
	"js":[]
}