{
	"error":0,
	"errorSummary":"",
	"errorDescription":"",
	"errorIsWarning":false,
	"silentError":0,
	"payload":{
		"url":"/save.php?controller=devices&action=add",
		"fields":[
			{
				"name":"name",
				"id":"name",
				"label":"Name",
				"tagname":"input",
				"type":"text",
				"required":true
			},
			{
				"name":"description",
				"id":"description",
				"label":"Description",
				"tagname":"input",
				"type":"text",
				"required":true
			},
			{
				"name":"email",
				"id":"email",
				"label":"Email",
				"tagname":"input",
				"type":"text"
			},
			{
				"name":"telephone",
				"id":"telephone",
				"label":"Telephone",
				"tagname":"input",
				"type":"text"
			},
			{
				"name":"company",
				"id":"company",
				"label":"Company",
				"tagname":"select",
				"source":"fillComboboxCompany.js"
			},
			{
				"name":"department",
				"id":"department",
				"label":"Department",
				"tagname":"select",
				"source":"fillComboboxDeparment.js?idCompany=[company]"
			}
		]
	},
	"resource_map":null,
	"css":[],
	"js":[]
}