{
	"error":0,
	"errorSummary":"",
	"errorDescription":"",
	"errorIsWarning":false,
	"silentError":0,
	"payload":{
		"url":"dataCompany.js",
		"columnID":"id",
		"fieldsList":[
			{
				"name":"name",
				"id":"name",
				"label":"Name",
				"tagname":"input",
				"type":"text",
				"required":true
			},
			{
				"name":"description",
				"id":"description",
				"label":"Description",
				"tagname":"input",
				"type":"text"
			},
			{
				"name":"contact",
				"id":"contact",
				"label":"Contact",
				"tagname":"input",
				"type":"text"
			},
			{
				"name":"telephone",
				"id":"telephone",
				"label":"Telephone",
				"tagname":"input",
				"type":"text"
			},
			{
				"name":"street",
				"id":"street",
				"label":"Street",
				"tagname":"input",
				"type":"text"
			},
			{
				"name":"Colonia",
				"id":"Colonia",
				"label":"Colonia",
				"tagname":"input",
				"type":"text"
			},
			{
				"name":"Ciudad",
				"id":"Ciudad",
				"label":"Ciudad",
				"tagname":"input",
				"type":"text"
			},
			{
				"name":"Estado",
				"id":"Estado",
				"label":"Estado",
				"tagname":"input",
				"type":"text"
			}
		]
	},
	"resource_map":null,
	"css":[],
	"js":[]
}